### ISSUE TITLE
Not Detecting Laptop as a Framework Laptop

### ISSUE THREAD

**Issue by tyme-dev** [Oganoth/Framework-Hub-PY#5]
I've downloaded the source code, installed the dependence, and ran the python file. 
The detector does not think that i have a framework laptop though. 

My CPU and GPU should up differently then was is expected for a AMD 13 it would appear

below is my log file:
2024-12-29 20:07:43,056 - framework_cc - INFO - Requesting administrator privileges...
2024-12-29 20:07:46,045 - framework_cc - DEBUG - Directory already exists: configs  
2024-12-29 20:07:46,045 - framework_cc - DEBUG - Directory already exists: libs
2024-12-29 20:07:46,045 - framework_cc - DEBUG - Directory already exists: assets
2024-12-29 20:07:46,045 - framework_cc - DEBUG - Directory already exists: fonts
2024-12-29 20:07:46,045 - framework_cc - INFO - Starting Framework Control Center...
2024-12-29 20:07:46,755 - framework_cc.gui - DEBUG - Font already installed: Ubuntu-Regular.ttf
2024-12-29 20:07:46,755 - framework_cc.gui - DEBUG - Font already installed: klingon font.ttf
2024-12-29 20:07:48,281 - framework_cc.gui - DEBUG - Looking for icon at: D:\code\Framework-Hub-PY\assets\logo.ico
2024-12-29 20:07:48,343 - framework_cc.gui - DEBUG - Looking for fonts at: D:\code\Framework-Hub-PY\fonts\Ubuntu-Regular.ttf and D:\code\Framework-Hub-PY\fonts\klingon font.ttf
2024-12-29 20:07:48,345 - framework_cc.gui - INFO - Loaded Ubuntu font from: D:\code\Framework-Hub-PY\fonts\Ubuntu-Regular.ttf
2024-12-29 20:07:48,345 - framework_cc.gui - INFO - Configuration loaded with language: en
2024-12-29 20:07:48,381 - framework_cc.gui - DEBUG - Screen dimensions: 2880x1920
2024-12-29 20:07:48,381 - framework_cc.gui - DEBUG - Window position: 2410,840
2024-12-29 20:07:48,402 - framework_cc - DEBUG - Loaded model configurations: ['13_AMD', '13_Intel', '16_AMD']
2024-12-29 20:07:48,402 - framework_cc - INFO - Model detector initialized with 3 models
2024-12-29 20:07:49,502 - framework_cc - INFO - Detected CPU: AMD Ryzen 5 7640U w/ Radeon 760M Graphics      
2024-12-29 20:07:49,542 - framework_cc - INFO - Detected GPUs: ['AMD Radeon(TM) 760M']
2024-12-29 20:07:49,542 - framework_cc - DEBUG - Has dedicated GPU: True
2024-12-29 20:07:49,542 - framework_cc - DEBUG - Checking model 13_AMD
2024-12-29 20:07:49,542 - framework_cc - DEBUG - Checking model 13_Intel
2024-12-29 20:07:49,542 - framework_cc - DEBUG - Checking model 16_AMD
2024-12-29 20:07:49,542 - framework_cc - WARNING - Could not detect Framework laptop model
2024-12-29 20:07:49,542 - framework_cc.gui - ERROR - No compatible Framework laptop detected
2024-12-29 20:07:49,542 - framework_cc - ERROR - Error in main: No compatible Framework laptop detected
2024-12-29 20:07:49,545 - framework_cc - ERROR - Traceback: Traceback (most recent call last):
  File "D:\code\Framework-Hub-PY\main.py", line 74, in main
    app = FrameworkControlCenter()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\Framework-Hub-PY\framework_cc\gui.py", line 183, in __init__
    raise RuntimeError("No compatible Framework laptop detected")
RuntimeError: No compatible Framework laptop detected

**Comment by Oganoth** [comment]
It's because of my last modifications on the model detector, I'll look at this in 1h +-

**Comment by tyme-dev** [comment]
still not detecting it

2024-12-30 20:56:06,634 - framework_cc - INFO - Requesting administrator privileges...
2024-12-30 20:56:09,326 - framework_cc - DEBUG - Directory already exists: configs
2024-12-30 20:56:09,326 - framework_cc - DEBUG - Directory already exists: libs
2024-12-30 20:56:09,326 - framework_cc - DEBUG - Directory already exists: assets
2024-12-30 20:56:09,326 - framework_cc - DEBUG - Directory already exists: fonts
2024-12-30 20:56:09,326 - framework_cc - INFO - Starting Framework Control Center...
2024-12-30 20:56:09,399 - framework_cc.gui - DEBUG - Font already installed: Ubuntu-Regular.ttf
2024-12-30 20:56:09,399 - framework_cc.gui - DEBUG - Font already installed: klingon font.ttf
2024-12-30 20:56:10,763 - framework_cc.gui - DEBUG - Looking for icon at: D:\code\Framework-Hub-PY\assets\logo.ico
2024-12-30 20:56:10,814 - framework_cc.gui - DEBUG - Looking for fonts at: D:\code\Framework-Hub-PY\fonts\Ubuntu-Regular.ttf and D:\code\Framework-Hub-PY\fonts\klingon font.ttf
2024-12-30 20:56:10,815 - framework_cc.gui - INFO - Loaded Ubuntu font from: D:\code\Framework-Hub-PY\fonts\Ubuntu-Regular.ttf
2024-12-30 20:56:10,815 - framework_cc.gui - INFO - Configuration loaded with language: en
2024-12-30 20:56:10,857 - framework_cc.gui - DEBUG - Screen dimensions: 2880x1920
2024-12-30 20:56:10,857 - framework_cc.gui - DEBUG - Window position: 2410,840
2024-12-30 20:56:10,895 - framework_cc - DEBUG - Loaded model configurations: ['13_AMD', '13_Intel', '16_AMD']
2024-12-30 20:56:10,895 - framework_cc - INFO - Model detector initialized with 3 models
2024-12-30 20:56:11,976 - framework_cc - INFO - Detected CPU: AMD Ryzen 5 7640U w/ Radeon 760M Graphics      
2024-12-30 20:56:12,027 - framework_cc - INFO - Detected GPUs: ['AMD Radeon(TM) 760M']
2024-12-30 20:56:12,027 - framework_cc - DEBUG - Has dedicated GPU: True
2024-12-30 20:56:12,027 - framework_cc - DEBUG - Checking model 13_AMD
2024-12-30 20:56:12,028 - framework_cc - DEBUG - CPU matches model 13_AMD
2024-12-30 20:56:12,028 - framework_cc - DEBUG - Checking model 13_Intel
2024-12-30 20:56:12,028 - framework_cc - DEBUG - Checking model 16_AMD
2024-12-30 20:56:12,028 - framework_cc - WARNING - Could not detect Framework laptop model
2024-12-30 20:56:12,028 - framework_cc.gui - ERROR - No compatible Framework laptop detected
2024-12-30 20:56:12,028 - framework_cc - ERROR - Error in main: No compatible Framework laptop detected
2024-12-30 20:56:12,030 - framework_cc - ERROR - Traceback: Traceback (most recent call last):
  File "D:\code\Framework-Hub-PY\main.py", line 76, in main
    app = FrameworkControlCenter()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\Framework-Hub-PY\framework_cc\gui.py", line 183, in __init__
    raise RuntimeError("No compatible Framework laptop detected")
RuntimeError: No compatible Framework laptop detected

**Comment by Oganoth** [comment]
I'll look at this asap ☺️

**Comment by Oganoth** [comment]
Made some change to the detector.py, can you try again now ?

**Comment by RikPi** [comment]
Hi, I had the same problem and now the application starts :)

**Comment by Oganoth** [comment]
Yay ! can you still send me your Log ? so i can do some more troubleshoot :D

**Comment by RikPi** [comment]
[2024-12-31.log](https://github.com/user-attachments/files/18280737/2024-12-31.log)
You can also see me trying to update the refresh rate as I was talking about in #6 :)

**Comment by Oganoth** [comment]
which CPU do you have on your Framework  13 ? 7640U with 760M or 7840U ?

**Comment by RikPi** [comment]
I have a 7840U
